Pass at markup
astoria-tech/FOIL-Request pull request #2
Opened 2020-08-04 23:23 UTC by bronzehedwick

Use 4 spaces and remove section comments. The 4 spaces should better
show the indentation, which intrinsically shows the section hierarchy
without the need for comments.

Add section tags around each distinct section.

Change the intro section from `h3` tags to a definition list. An `h3` needs to
follow an `h2` always, and a definition list semantically reflects the "key
value pairs" nature of that structure.

Wrap each letter segment in wrapping markup with classes. I'm skipping
ahead a bit to add some extra HTML I know we'll need when styling.

Add a `small` tag around the copyright notice, as that tag has been
re-utilized for legal text since HTML 5.

Rename some of the IDs to make better sure they won't collide with
anything. Have the in-page links go directly to the appropriate heading;
we don't need a wrapping anchor tag.

Use the details/summary widget for native show/hide functionality for
the expandable menu.

TODO add back to top links, and menu icon.

2020-08-05 11:24 UTC, aniagaska requested changes
It looks like in the appeal letter's letter-segment_body is missing and instead is replaced by the annotations text

2020-08-05 22:57 UTC, bronzehedwick commented
Hi @aniagaska, I took a look at the code and I'm finding the letter body for the appeal section.

<img width="1727" alt="Screen Shot 2020-08-05 at 6 52 09 PM" src="https://user-images.githubusercontent.com/637174/89471999-7397c000-d74d-11ea-8bef-42d272821a42.png">


Am I looking in the wrong place? Are you referring to something else?

Thanks!

2020-08-05 23:14 UTC, bronzehedwick commented
I also updated my PR to take a pass at the `resources.html` file.

2020-08-06 12:35 UTC, aniagaska commented on index.html
> +            <h3>Include a description of the records and when they were requested</h3>
There's something missing here

2020-08-06 12:39 UTC, aniagaska requested changes
We're still missing the letter body where there is space to show that the letter needs to be filled in with details 

>  <p>I hereby appeal the denial of access regarding my request, which was made on </p> <!-- bars indicating filling the space with text -->

2020-08-06 12:57 UTC, aniagaska commented
![markup1](https://user-images.githubusercontent.com/44368856/89533097-dbd3b980-d7c0-11ea-8ac4-24f025dbb4b3.JPG)

I made comments where the body is confused with an annotation, and the body is missing because it had a comment after it writing that it had to have bars after it to show that the content had to be filled in

2020-08-06 13:02 UTC, aniagaska commented
> Hi @aniagaska, I took a look at the code and I'm finding the letter body for the appeal section.
> 
> <img alt="Screen Shot 2020-08-05 at 6 52 09 PM" width="1727" src="https://user-images.githubusercontent.com/637174/89471999-7397c000-d74d-11ea-8bef-42d272821a42.png">
> 
> Am I looking in the wrong place? Are you referring to something else?
> 
> Thanks!

It's something else! Those look good! I added comments, hopefully its more clear now.

2020-08-06 16:10 UTC, aniagaska reviewed
The end of the document serves as a conclusion and should be treated similar to the introduction in terms of styling and markup
`<div class="letter-segment">
                <h3 class="letter-segment__heading">If your appeal is rejected, then you can go to court </h3>
                <p class="letter-segment__body">Judicial review of a final agency denial Article 78 of Civial Practice Law and Rules.</p>
            </div>

            <div class="letter-segment">
                <h3 class="letter-segment__heading">FOIL Attorney fees may be awarded to a member of the public</h3>
                <p class="letter-segment__body"><a href="https://www.dos.ny.gov/coog/news/december2017.html">a mandatory fee is rewarded</a> if the court finds that the agency had no reasonable basis for denying access</p>
            </div>`

2020-08-06 16:50 UTC, merged